# Generated by Django 3.2.18 on 2023-02-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
