# Generated by Django 4.1.7 on 2023-02-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0002_auto_20230218_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='department',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='department',
            name='vision',
        ),
        migrations.CreateModel(
            name='DeptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('overview', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.department')),
            ],
            options={
                'verbose_name': 'deptdetail',
                'verbose_name_plural': 'deptdetails',
                'ordering': ('name',),
            },
        ),
    ]
