# Generated by Django 4.1.7 on 2023-02-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0003_remove_department_mission_remove_department_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=300)),
                ('phn_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('dept', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=300)),
                ('purpose', models.CharField(max_length=300)),
                ('materials', models.CharField(max_length=300)),
            ],
        ),
    ]
