# Generated by Django 4.1.7 on 2023-02-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
