# Generated by Django 4.1.7 on 2023-02-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0009_alter_student_course_alter_student_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='materials',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
