# Generated by Django 4.1.7 on 2023-02-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0012_delete_deptdetail_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='materials',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
