# Generated by Django 4.1.7 on 2023-02-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0013_alter_student_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='materials',
            field=models.CharField(max_length=300),
        ),
    ]
