# Generated by Django 4.1.7 on 2023-02-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0014_alter_student_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
