# Generated by Django 4.1.7 on 2023-02-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0015_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AlterField(
            model_name='student',
            name='materials',
            field=models.BooleanField(),
        ),
    ]
